#!/usr/bin/with-contenv bash

if [ -z "$DEVTOOLS_PRIVATE_KEY" ]; then

  echo "##############################################################"
  echo "DEVTOOLS_PRIVATE_KEY is not set. You will not be able to clone "
  echo "private repositories. You can set this variable with"
  echo "    export DEVTOOLS_PRIVATE_KEY=\"\$(cat ~/.ssh/id_rsa)\""
  echo "##############################################################"
  exit  

fi

echo "DEVTOOLS_PRIVATE_KEY exists. Setting up key..."

mkdir /root/.ssh

# Determine the proper file name
if [[ "$DEVTOOLS_PRIVATE_KEY" =~ "BEGIN DSA" ]]; then
    KEY_NAME="id_dsa"
elif [[ "$DEVTOOLS_PRIVATE_KEY" =~ "BEGIN RSA" ]]; then
    KEY_NAME="id_rsa"
else
  echo "Private key is not DSA or RSA format."
  exit
fi  

# Create the key file with the proper permissions
echo "$DEVTOOLS_PRIVATE_KEY" > /root/.ssh/$KEY_NAME
chmod 600 /root/.ssh/$KEY_NAME

# Make sure that commands don't need to prompt for host keys
ssh-keyscan -H bitbucket.org >> /root/.ssh/known_hosts
ssh-keyscan -H github.com >> /root/.ssh/known_hosts
